export enum ProductCategory {
  MELA_WHITE = 'mela white',
  ESSENTIAL = 'essential',
  HYDRATING = 'hydrating',
  REGULATING = 'regulating',
  SENSITIVE = 'sensitive',
  BEAUTY_ELEMENTS = 'beauty elements',
  VITALITY = 'vitality',
  BODY_SCIENCE = 'body science',
  HAIR = 'hair',
  MEN = 'men',
  GREEN_PEEL = 'green peel',
  NIGHT_CARE = 'night care',
  BODY_CARE = 'body care',
  AMPOULE = 'ampoule',
  DRY_SKIN = 'dry skin',
}
